# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  provisioning_script_url = "https://gist.githubusercontent.com/hyunsuk/8529a9bcad5aabb993ce8e69005a1999/raw/daee2d01afef1338674cfde7968efefba915a81e/djangogirls.sh"

  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.define "djangogirls"
  config.vm.hostname = "djangogirls"

  config.vm.synced_folder "../",
    "/home/ubuntu/djangogirls",
    owner: "ubuntu",
    group: "ubuntu"

  config.vm.provision "shell", privileged: false, path: provisioning_script_url

  config.vm.provider :virtualbox do |vb|
    vb.name = "djangogirls"
    vb.cpus = 2
    vb.memory = 1024
  end
end
